### ISSUE TITLE
update dialog to respond to the keyboard commands suggested by MacOS voice-over (Control Option Shift Down arrow)

### ISSUE THREAD

**Issue by karinamzalez** [CMSgov/design-system#1647]
**Describe the bug**
- the keyboard commands suggested by voice-over (Control Option Shift Down arrow) to select the button do not work - confirmed that this is the same issue for all CMS modal components. However, the user's focus is still taken inside of the modal component and they can access all links within this modal window by tabbing. 

**To Reproduce**
1. Turn on MacOS screen reader
2. Go to CMS dialog component
3. Use suggested command to interact with dialog Control Option Shift Down arrow
4. Notice command does not guide user to interact with Dialog 

**Expected behavior**
Suggested command by voiceover, should help user interact with Dialog content

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by pwolfert** [comment]
@karinamzalez, this issue was fixed when we switched to using the HTML `<dialog>` element in our dialogs. That fix is available since [version 5.0](https://github.com/CMSgov/design-system/releases/tag/%40cmsgov%2Fdesign-system%405.0.0). We should also point out that the VoiceOver + Chrome combo produces unexpected results. [Deque recommends using Safari with VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) for best results.
