### ISSUE TITLE
Dialogs / Modal component

### ISSUE THREAD

**Issue by asarazor** [CMSgov/design-system#193]
## Description

We have a need for a general purpose dialog component in our products at HHS OIG. [Here's a gov.uk example for reference](http://rural-payments-styleguide.herokuapp.com/dialogs/) of what we are considering. Does the core team have a dialog component on the roadmap?

If not, we will look at implementing our own.

**Comment by sawyerh** [comment]
@asarazor We have a ticket for a modal in our backlog (which we're working to make more public). So far there hasn't been a need for a modal component on the projects currently using design system. 

If this is something your team would like to take on, contributions are always welcome 😄 Otherwise, the team will discuss prioritizing this ticket for an upcoming sprint soon. @1Copenut shared a link to [react-aria-modal](https://github.com/davidtheclark/react-aria-modal), which looks like it could be a good starting point.

**Comment by sawyerh** [comment]
@asarazor quick update: we've prioritized this for our upcoming sprint, which goes from November 23 – December 6. We'll use this GitHub issue to track it's progress.

**Comment by asarazor** [comment]
That's great news. Thanks folks.

FWIW, we are not averse to contributing components of this nature in the future. This time we'll let you take the lead!

**Comment by sawyerh** [comment]
Tagging a related discussion: https://github.com/18F/web-design-standards/issues/911
