### ISSUE TITLE
Calendar Picker changes the Hint text label from "MM/DD/YYYY" to date entered when text input area has focus

### ISSUE THREAD

**Issue by bedwar2** [CMSgov/design-system#2307]
**Describe the bug**
The Calendar Picker has 3 general components:  label, the hint text below the label and the text box with button to drop down a calendar and pick a date.   This issue is with the hint text which should always display "MM/DD/YYYY" (as shown below).   
![image](https://user-images.githubusercontent.com/15959308/209228095-fe36cbf7-2e0a-4960-a8ce-586a529e5f4e.png)

However, due to some code to announce the date on the screen reader that appears to possibly be backwards, the actual date the user entered shows up there as below:
![image](https://user-images.githubusercontent.com/15959308/209228194-af838f2f-b755-4ce4-a03d-708dfe7fb9f0.png)

What I found was that it appears that there are 2 span tags there.   One is the "MM/DD/YYYY" and the other has a class "ds-u-visibility--screen-reader" which I assume was meant to announce the chosen date?   What happens is the one with "MM/DD/YYYY" gets the "ds-u-visibility--screen-reader" class while the one with the date in it gets the attribute _aria-hidden='true'_.   I believe the intent was for this to be reverse.   Here is screen shot of HTML when a selected date is there and the input text box has the focus:
![image](https://user-images.githubusercontent.com/15959308/209228644-8cca08af-ad0c-4278-b546-00da6ee7bf64.png)
As you can see the ds-u-visiblity-screen-reader class would make more sense on the span with "12/01/2022" in it so that the MM/DD/YYYY continues to show (and perhaps aria-hidden="true" would be swapped to that first span tag).

Here is the HTML prior to date selection:
![image](https://user-images.githubusercontent.com/15959308/209228695-151d69b1-16c1-4bf9-9f48-6669658f326f.png)

**To Reproduce**
1. Go to Story Book at [https://design.cms.gov/storybook/?path=/story/components-singleinputdatefield--with-picker&globals=theme:core] 
2. Select a date using the calendar picker and then ensure the focus is in the text box input area (not the button)
3. If you tab out of that area, the hint text goes back to the proper "MM/DD/YYYY"

**Expected behavior**
The hint text MM/DD/YYYY displays at all times (remains static) while the screen reader only tag contains the date selected instead of the display span tag.

**Screenshots**
See screenshots above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 108
But note - it's an HTML issue so all OS's/Browsers would show this

**Smartphone (please complete the following information):**
See note above - it's not a device specific issue.

**Additional context**
None

**Comment by pwolfert** [comment]
Hi @bedwar2 👋,

What you’ve described is actually how we intended for this component to work. For background, this component aimed to address accessibility issues with the state of the art in the common input-masking pattern. Traditional masked inputs modify the value of an input while the user types, which is a confusing and frustrating experience for people using screen readers. We recognized this issue long ago when creating our [existing masked field](https://design.cms.gov/components/masked-field/) and relegated the input-modification phase of the interaction to happening only after the user blurs away from the input rather than modifying it in place in realtime.

However, sighted users are accustomed to that realtime feedback that an input mask provides, so we took that feedback and went back to the drawing board for this new component. decided to implement [this idea by Brad Frost](https://bradfrost.com/blog/post/labelmask/). It gives instant feedback to sighted users about the data they’re inputting while also minimizing the noise for screen readers. We worked with an accessibility expert to tune the screen-reader experience. This has yet to be fully validated in user testing, but it’s how we decided to implement the new date field. 

We've actually been [working on a documentation page](https://github.com/CMSgov/design-system/pull/2309) for this new label-masked field pattern beyond its use in the calendar picker. Please let us know if you have any feedback about component API or the documentation we've written. We plan to publish it in the next release.
