### ISSUE TITLE
Calendar Picker Component allows for unlimited entry of numbers

### ISSUE THREAD

**Issue by bedwards-cms** [CMSgov/design-system#2594]
**Description**

Include a high-level description of the issue. 
When keying in the date field, the calendar picker allows an unlimited number of digits to be entered.   I did observe there isn't a maximum length on this textbox - I know even if one is added user could still type 2 extra digits if they enter the number without the "/" characters.    Just a minor issue but may be helpful to limit entry.  

In addition, letters are allowed to be entered as well.  May be worth restricting to numbers and "/" only.

**Steps to reproduce the issue**

1. Click on date field and enter a bunch of numbers

**Additional information [optional]**
![image](https://github.com/CMSgov/design-system/assets/135224593/6f73c427-5847-4eae-b9c8-b4b511580dee)

**Comment by zarahzachz** [comment]
For this component, this was an intentional decision. 

We left the text field to accept unlimited characters because interfering with user's input was flagged as an a11y issue (user may not be typing but dictating, for instance). The characters are also formatted and truncated on blur when the user has intentionally moved focus indicating they're good. The masking that appears above it is meant to inform users of what data is then passed to wherever and how its formatted.
