### ISSUE TITLE
Spinner does not cover Dialog

### ISSUE THREAD

**Issue by dmethvin-gov** [CMSgov/design-system#2770]
**Describe the bug**
When a Dialog component initiates an action that requires a Spinner component to appear, such as a remote data loading action, the Spinner does not cover the Dialog and the Dialog remains active to the user. This is because HTML dialog elements live in their own layer above all the page content. 

It's possible to fix this by using a dialog element for the spinner, because a newly opened dialog covers any that are currently open. I've created a minimal JS/CSS/HTML to demonstrate the issue which makes it easier to reproduce with basic markup than trying to pull in all of React and CMSDS components. It still needs some a11y work so it's not finished.

[dialog-demo.html.txt](https://github.com/CMSgov/design-system/files/13116035/dialog-demo.html.txt)

**To Reproduce**
1) Rename the demo file to .html and load in the browser.
2) Click the Open dialog button. The dialog should appear in the center of the screen.
3) Click the Show dialog spinner button. The spinner should cover the dialog and the rest of the page is inert. Click the spinner to close it.
4) With the dialog still open, click the Show normal spinner. The dialog will stay on top of the spinner and remain active, but the rest of the page is inert.
5) Click the Close button on the dialog. Note the spinner was present behind the dialog. Click the spinner to close it.

**Expected behavior**
The Spinner should cover and inactivate the Dialog when it appears.

**Screenshots**
![Screen Shot 2023-10-24 at 10 11 40 AM](https://github.com/CMSgov/design-system/assets/40182224/8541a281-e21b-47b1-8963-6e983e4e870d)
Dialog open, no spinner

![Screen Shot 2023-10-24 at 10 11 52 AM](https://github.com/CMSgov/design-system/assets/40182224/a6a38f89-79ec-4759-b0f0-ef697dfbff87)
Dialog open, dialog-based spinner

![Screen Shot 2023-10-24 at 10 12 14 AM](https://github.com/CMSgov/design-system/assets/40182224/9fe1b2f2-a118-4386-8d2a-2129c41c82a5)
Dialog open, standard spinner

![Screen Shot 2023-10-24 at 10 16 33 AM](https://github.com/CMSgov/design-system/assets/40182224/cb88f40b-5a0e-4ec9-a171-3b00c682e37a)
Dialog closed, standard spinner

**Additional context**
References:
* [`dialog` on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)
* CMSDS Spinner - [JS](https://github.com/CMSgov/design-system/blob/main/packages/design-system/src/components/Spinner/Spinner.tsx), [CSS](https://github.com/CMSgov/design-system/blob/main/packages/design-system/src/styles/components/_Spinner.scss)

**Comment by pwolfert** [comment]
Hi @dmethvin-gov!

The spinner component that we have in the design system is meant to be flexible and simple enough to use in any context that the application needs—from inside buttons to being a placeholder for content. It would be outside the scope of its design to force it to display above everything else, and in fact we can't for the very reasons you've shown with your example (because browser-made dialogs render above everything else). This is an example of something we'd place in the realm of application responsibility.

But perhaps I'm not understanding the request. What is it you're trying to do exactly? This is not a pattern we've seen used so far in healthcare.gov or medicare.gov or any other apps that we've seen using the design system.

**Comment by dmethvin-gov** [comment]
No, you understood correctly. I have a dialog and want a modal spinner to appear when something in the dialog causes it to need to appear. We don't want the user to interact with the dialog while it's in the middle of exchaning data with the server, for example. 

I see your point about the spinner though, since the examples show it spinning on a button and in that case it should be contained by the element it's within. So our use case isn't a good match for it. We'll need to create a custom component for it.

**Comment by brentschneider** [comment]
Hi @dmethvin-gov 

Before responding, I want to confirm my read on the interaction presented

On submit, the spinner appears over everything on the page in order to disable any interactions on the page until the data status returned changes the state?

_this could be the data submitted was a success, or it could be failed- try again._

What you are after is interaction guidance that does not disrupt the flow— is that correct?

**Comment by dmethvin-gov** [comment]
@brentschneider Your description sounds accurate. The data submit/fetch are async and there is a central location in the app that manages whether the spinner needs to be shown or not. The user may take actions in the dialog that require remote data. In that case, the data in the dialog may need to be changed and we want to ensure the data user doesn't, for example, start editing a field that a few seconds later will be updated from the server.

**Comment by brentschneider** [comment]
Dave, I saw you closed this issue on GH.  
Did you want to continue the convo over in the #**cms-design-system-team slack?**

**Comment by dmethvin-gov** [comment]
Reviewing the use cases for the current Spinner, it made sense to me why it wouldn't show over a Dialog. So I'm good with that. Thanks!
