### ISSUE TITLE
Wrong code on NPM for 7.0.7 release

### ISSUE THREAD

**Issue by hundt-corbalt** [CMSgov/design-system#2774]
I updated to 7.0.7 to get [this commit](https://github.com/CMSgov/design-system/commit/b25ce40bd0c3d78bcc098b3fea26dacd5cd57018). If you look at

https://github.com/CMSgov/design-system/blob/%40cmsgov/design-system%407.0.7/packages/design-system/src/components/Tabs/TabPanel.tsx

You can see the commit applied:

<img width="240" alt="image" src="https://github.com/CMSgov/design-system/assets/79656825/d3ff5fbb-abcd-4c19-abea-da1d56f4d241">

But the actual code uploaded to NPM does not seem to include this commit:

https://www.npmjs.com/package/@cmsgov/design-system/v/7.0.7?activeTab=code

<img width="154" alt="image" src="https://github.com/CMSgov/design-system/assets/79656825/a03fcb39-315d-4173-9931-f87c3fc27ee9">

**Comment by pwolfert** [comment]
@hundt-corbalt, it's strange that that commit is showing up under the `@cmsgov/design-system@7.0.7` tag, and I still haven't figured out why. We didn't release it until [v8.0.0](https://github.com/CMSgov/design-system/releases/tag/%40cmsgov%2Fdesign-system%408.0.0). I think something went wrong with our release tagging, because our intention wasn't to release it until 8.0.0.

It's also curious how the commit is in the history of that tagged release commit, and yet our publishing infrastructure that checks out a specific tag didn't publish code with that commit to npm. I can see in the 7.0.7 publishing logs that `@cmsgov/design-system@7.0.7` was checked out. If I check out that tag locally, I see the tab commit in the commit log. If I check out the commit that our publish job was on after it checked out that tag, the tab commit is not in the commit log. So at this point I'm not sure if it's a bug in our publish job or in our release script that tags the commit. Based on the evidence in git, it seems more likely that it's a problem with the publish job in Jenkins.

Thanks for bringing that to my attention!
