### ISSUE TITLE
Update Sketch file

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#331]
Currently, the sketch file has items that are not in the design system and the design system has code components that are not in the [Sketch file](https://github.com/CMSgov/design-system/blob/master/design-assets/Design%20system%20UI%20kit.sketch). 

## Fonts missing
Maybe we need to tell folks to make sure they have the following installed? Follow on work #334

![screen shot 2019-02-18 at 10 11 00 am](https://user-images.githubusercontent.com/1449852/52959920-83f38980-3365-11e9-9f5e-652f32933c5a.png)

## Colors
Sketch file has special state colors defined but they are not in the code. - Follow on work #352

### Buttons
- [x] Sketch file is missing inverse buttons
- Sketch file is missing buttons with icons - Follow on work #354

### Badge
- [x] Sketch file is missing large text version

### Checkbox and radio
- [x] Sketch file is missing inverse versions
- [x] Sketch file is missing right to left version
- [x] Sketch file is missing hint text and errors 

### Select 
- [x] Sketch file is missing different sizes
- [x] Sketch file is missing inverse versions

### Date field
- [x] Sketch file is different than code (which is the source fo truth?)
- [x] Sketch file is missing error example

### Table 
- [x] Sketch file is different than code (which is the source fo truth?) 

### Tabs
Sketch file is different than code (which is the source fo truth?) Follow on work - #353

### Text field
- [x] Sketch file is different than code (which is the source fo truth?). Sketch file is missing labels and hint text. 
- [x] Sketch file is missing disabled text field
- [x] Sketch file is missing inverse versions 

### Vertical navigation
- [x] Sketch file is different than code (which is the source fo truth?)

## Missing components from Sketch file
Follow on work #355

### Missing patterns from Sketch file
- [x] Documentation page
- [x] Review
- [x] Step List

**Comment by melwoodard** [comment]
@line47 have a look as well at the ds-healthcare-gov-ui-kit file: https://drive.google.com/drive/folders/0B6rLIk15jJFUUEJnSnAzaVZUZFk

This is meant to be the site package-specific sketch file for healthcare.gov, and it contains some of the missing components/states you mentioned above. I don't have much history on it, but from what I can tell it seems to have been kept more up to date than the main sketch file, though it's also missing some things the main file has.

The only parts of that file that I see as truly healthcare.gov specific are the primary colors, header and footer, and I'd be curious how we could still accommodate those for healthcare.gov's purposes without maintaining two separate files. Something to chew on, and maybe separately from this.

Some other improvements I'd like to see in the Sketch file, which aren't component specific but would improve overall usability:

- Reworking symbol construction for better responsive behavior - currently resizing some symbols skews their proportions
- Improve naming and organization of symbols, text styles, and layer styles - ensure naming matches what's used in the documentation, revisit submenus
- Explore providing sample page templates - the healthcare.gov UI kit file has templates for a step list page and a form page. Can we bring these in, and are there others we think would be useful? Maybe an app landing page like https://localhelp.healthcare.gov/ ?

**Comment by line47** [comment]
@melwoodard Can you make 3 new issues from those bullet points ☝️

**Comment by melwoodard** [comment]
Done!

**Comment by jenniferthibault** [comment]
@line47 I have been working with the sketch file for a CMS app for Electronic Advanced Planning Documents (Repo: https://github.com/18F/cms-hitech-apd )

👋 @melwoodard any chance you could zip that Healthcare.gov sketch file and upload it here? I'd love to take a look, since I've probably been working on some of the same improvements, but I don't have access to that drive folder.


Two additional oddities for the Sketch file list:

## The grid layout
For large/desktop screens (haven't yet checked the mobile/tablet), the grid layout uses measurements that don't conform with spacing or responsive layout guidance in the system (either in the site docs, or in the code).

The artboard width for standard desktop is set to 1104, which seemed non-standard and confusing.
![screen shot 2019-02-19 at 8 39 41 pm](https://user-images.githubusercontent.com/11636908/53059894-8c8fb100-3486-11e9-9020-c8d89b0e293a.png)

Since the [Responsive design](https://design.cms.gov/guidelines/responsive/) guidance sets `$width-lg` to 1024px wide viewports, I expected the grid the be built to a display 1024px wide. Instead, it's built to 1040px wide. Here's a screenshot of the grid layout settings for the desktop view:
![screen shot 2019-02-19 at 8 06 53 pm](https://user-images.githubusercontent.com/11636908/53059419-bba52300-3484-11e9-9f10-7359a8da01ca.png)
- Also note that with the current settings, the gutter width does not conform to the 8-pixel grid for gutters

Based on a 1024px viewport, I'd expect that to use these settings instead:
![screen shot 2019-02-19 at 8 22 45 pm](https://user-images.githubusercontent.com/11636908/53059475-dd9ea580-3484-11e9-94cf-fe315536cc85.png)
- These settings also conform to the 8-pixel grid for gutters

I've rebuilt the grid in my working file using those measurements, but have been updating the components only as needed since I'm trying to be incremental and the components are built on that first weird grid size. Glad to submit this back, but need to figure out how to extricate it.  All ears here 👂 

## Grid construction
It took @hbillings and I a while to deconstruct the grid in the code in order to start building more seamlessly between design and dev. For example:

- We expected to see a grid that is built like this, where the gutter is made of margins:
  - <img width="712" alt="screen shot 2019-02-14 at 11 12 40 am" src="https://user-images.githubusercontent.com/11636908/52811252-7da19c80-3049-11e9-9fcf-a2cb1aca3750.png">

- And discovered a grid that is built like this, with the gutter is built of padding:
  - <img width="712" alt="screen shot 2019-02-14 at 11 13 39 am" src="https://user-images.githubusercontent.com/11636908/52811312-a1fd7900-3049-11e9-81bd-43524df71605.png">

This could be marked up in the Sketch file and/or the documentation site to make it more clear. (And now would be an excellent time for someone else to point out that we are wrong in how we're understanding this construction!!)

**Comment by jenniferthibault** [comment]
I hadn't refreshed my page since the earlier comments, so now looks like you're in favor of separate issues for this type of feedback — glad to do that if you'd like!

**Comment by melwoodard** [comment]
@jenniferthibault 🙇‍♀️ that would be wonderful. Here's the healtcare.gov UI kit file, have at it and let us know if you have thoughts on useful things to pull out from there. Though there's a lot of overlap of components, it's set up pretty differently from the core sketch file.

[ds-healthcare-gov-uikit.sketch.zip](https://github.com/CMSgov/design-system/files/2885254/ds-healthcare-gov-uikit.sketch.zip)

**Comment by line47** [comment]
If you could abstract this issue out into a separate issue @jenniferthibault that would be 💯

**Comment by jenniferthibault** [comment]
👋 @line47 I've been rebuilding a lot of the sketch file to make it more complete and more usable for our project. Here's what I have so far: 📁 [CMS Design System UI kit.sketch.zip](https://github.com/CMSgov/design-system/files/2903731/CMS.Design.System.UI.kit.sketch.zip)

In it, I've re-created your list below and checked off what my file incorporates with green check icons so they're easy to spot. In addition to those changes, I've also make a few modifications that have made it easier for **me** to use the file, including:

- Broke up the file structure into separate Pages to help better line up with how the documentation site is organized (aligned with #339 )
  - ![screen shot 2019-02-25 at 10 56 57 pm](https://user-images.githubusercontent.com/11636908/53386698-3e305580-3951-11e9-97e1-9ad1de94119b.png)

- Renamed some components to better match the documentation site (also aligned with #339). One difference is I grouped "Form controls" together because there are so many itty bitty field pieces that otherwise get sub-menu'd so deeply that they're hard to access. Form controls lines up with the [USWDS's organization](https://v2.designsystem.digital.gov/components/form-controls/) so I might recommend this system go one step further and match how they've categorized their elements completely.
  - ![screen shot 2019-02-25 at 11 01 26 pm](https://user-images.githubusercontent.com/11636908/53386716-52745280-3951-11e9-8c17-f0473684f550.png)
- Used one artboard per type of component so they're easier to find (except for form controls, which are grouped)
- Improved responsiveness of some components
- Created a `Layout` page that intends to show how to use the responsive grid in relation to responsive breakpoints declared on the documentation site. It's based on my understanding from #344 so if that's wrong, this is wrong in the same ways. 
- Flagged when components aren't built of re-usable symbols (but didn't flag when they don't match the code, because I wasn't sure how they were out of line yet: see tables/tabs)
- Left gigantic bright pink boxes in areas where there are known holes/questions/or differences
- REMOVED the accordion layers from the file, which are NOT in the code. These were particularly confusing to me, but I'm guessing they are just USWDS leftovers?
- In all places where the sketch file and code were different, I chose the code on the Documentation site as the source of truth.

I'd understand if these don't work for the whole thing, but wanted to share! If you're interested in using this, I'm glad to help refine it further.
____ 


> ## Colors
> * [ ]  Sketch file has special state colors defined but they are not in the code.
> 
> ## Components
> ### Buttons
> * ✅  Sketch file is missing inverse buttons
> * [ ]  Sketch file is missing buttons with icons
> 
> ### Badge
> * ✅  Sketch file is missing large text version
> 
> ### Checkbox and radio
> * ✅  Sketch file is missing inverse versions
> * ✅  Sketch file is missing right to left version
> * ✅  Sketch file is missing hint text (✅ )  and errors (🔴 didn't do this)
> 
> ### Select
> * ✅  Sketch file is missing different sizes
> * ✅  Sketch file is missing inverse verson
> 
> ### Date field
> * ✅  Sketch file is different than code (which is the source of truth?) ✅ rebuilt based on example from the documentation site
> * ✅  Sketch file is missing error example
> 
> ### Table
> * [ ]  Sketch file is different than code (which is the source fo truth?)
> 
> ### Tabs
> * [ ]  Sketch file is different than code (which is the source fo truth?)
> 
> ### Text field
> * ✅  Sketch file is different than code (which is the source fo truth?). 
> * ✅ Sketch file is missing labels and hint text.
> * ✅  Sketch file is missing disabled text field
> * ✅  Sketch file is missing inverse versions
> 
> ### Vertical navigation
> * ✅  Sketch file is different than code (which is the source fo truth?) — 
> 
> ## Missing components from Sketch file
> * [ ]  Autocomplete
> * [ ]  Help drawer
> * [ ]  Masked input (phone, social security number, zip code)
> * [ ]  Modal dialog
> * [ ]  Month picker
> * [ ]  Spinner

**Comment by line47** [comment]
Oh wow! This is 💯 I'm sure we will be able to incorporate this work. I have a PR open where I was adding the buttons and patterns. Maybe we can grab the patterns from my Sketch file and combine with all this great work you have done 🌺

**Comment by jenniferthibault** [comment]
Woo! I was definitely making this file with me as the primary user in mind, so I'd totally understand if you want or need to rework any of aspects for a wider group of your users. 

And also, yay to those icon buttons in #347!! Those are such a bear to build. I'm definitely going to grab those and make iterations in each color in my sketch file 😺

**Comment by line47** [comment]
Closing this in favor of smaller more detailed issues
