### ISSUE TITLE
Define path for folks onboarding to the Design System - using site packages

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#365]
- Is this document what folks follow?
https://github.com/CMSgov/design-system/blob/master/guides/SITE-PACKAGES-AND-THEMES.md

- What can we learn from the Healthcare.gov site package
  - we should talk to the folks that worked on this site package
@pwolfert seems like the most likely person
https://github.cms.gov/CMS-WDS/ds-healthcare-gov 

-  Who else is using a site package and do they have documentation they are following?

- This description is great and should be in the site-packages documentation in this repo as well - 
https://github.cms.gov/CMS-WDS/ds-healthcare-gov#why-a-site-package

**Comment by line47** [comment]
thoughts here @phiden or @ClassActHarris

**Comment by phiden** [comment]
I think it's a blank slate. Any process we have is ad hoc at best. It seems like the path you're on -- to figure out how people are onboarding now and then using that as a starting point -- is a good one.

**Comment by line47** [comment]
From Ben: In the context of Design System's use within CMS, I think we should also provide guidance to programs on how to approve of and include new patterns within their site-packages.

**Comment by line47** [comment]
What's the difference between a site package and a theme? @pwolfert can you explain?
The only information i can find is on site packages

**Comment by pwolfert** [comment]
Relationship: A site package is a theme, but a theme is not necessarily a site package.
In reality a "site package" is only a "site package" because that's what we've called it. We wanted it to be what all our apps across HC.gov use to customize the design system and add shared functionality that's not necessarily helpful to the entire design system—like a site header for healthcare.gov. The word "theme" didn't really capture what the site package would be in its entirety since we were adding new components and patterns and not just overriding some css variables.

**Comment by line47** [comment]
From what I gather:

- a theme would be if you are modifying **style** - colors, fonts, spacing, etc...
- A site package would be when new components are created in addition to possible theming mentioned above.

Does that sound right?

**Comment by line47** [comment]
This relates to https://jira.cms.gov/browse/WNMGDS-158 in JIRA

**Comment by line47** [comment]
This issue has been completed
