### ISSUE TITLE
Add React Router support to vertical nav component 

### ISSUE THREAD

**Issue by kingishb** [CMSgov/design-system#488]
## What
Hi there! We'd like support for [react router](https://reacttraining.com/react-router/web/guides/quick-start) style links in the vertical nav or some other way way to invoke `Link` to react components when building out navigation

## Why
We are trying to use the vertical nav in a project that routes pages based on react routes rather than hrefs. Right now the vertical nav takes in `urls` which don't seem to compose well with react router.

If there's a way to do this already please let me know!

**Comment by bernardwang** [comment]
Hi @kingishb, thank you for submitting this issue! Currently the only way to make VerticalNav work with react router is to use the `onClick` handler and manually call `history.push`. We are working on a solution that allows for custom link rendering, so that instead of using the `onClick` handler you can choose to render a `<Link>` element instead of the default `<a>` tag. I'm hoping to get that solution in for the next release in 2 weeks! Let me know if that helps or if you have any other questions!

Ticket tracked here: https://jira.cms.gov/browse/WNMGDS-292

**Comment by bernardwang** [comment]
In the next release VerticalNav will have a ‘component’ prop that you can use to render ‘<Link>’ and custom components
