### ISSUE TITLE
Checkbox and Radio: Checkmarks show as clipped in Windows High Contrast Mode

### ISSUE THREAD

**Issue by davidakennedy** [CMSgov/design-system#568]
**Describe the bug**
If you're using Windows High Contrast Mode, the checkmarks in the checkbox and radio button component appear cut off or clipped.

**To Reproduce**
1. Enable High Contrast Mode on a Windows machine. Settings > Ease of Access > High Contrast
2. View: https://design.cms.gov/components/choice/
3. See the clipped checkmarks.

**Expected behavior**
The checkmarks should appear in their whole shape like they do normally.

**Screenshots**
<img width="196" alt="Checkmarks in high contrast mode" src="https://user-images.githubusercontent.com/1473618/70632236-6ea16180-1bfc-11ea-85a9-d57fdf572ea4.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version:  44.18362.387.0

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-327

**Comment by line47** [comment]
I'm seeing no checkmarks at all on Windows 7 enterprise in IE11 High Contrast Mode 

![Screen Shot 2020-06-15 at 2 12 33 PM](https://user-images.githubusercontent.com/1449852/84691731-9d352780-af12-11ea-9a59-f14ba336fc3a.png)

It looks like this is because we use a background image to render the box and checkmark and high contrast mode does not render background images https://terrillthompson.com/182

USWDS has the same issue as they render background images
![Screen Shot 2020-06-15 at 2 16 27 PM](https://user-images.githubusercontent.com/1449852/84692193-79beac80-af13-11ea-899f-5b4980199c98.png)

However, it looks like Gov.uk uses styles to draw the checkmark, which works in high contrast mode. I'm thinking we should move in this direction to ensure this works for high contrast modes.


![Screen Shot 2020-06-15 at 2 20 19 PM](https://user-images.githubusercontent.com/1449852/84692483-ee91e680-af13-11ea-9665-4b062b8fd77f.png)
![Screen Shot 2020-06-15 at 2 23 55 PM](https://user-images.githubusercontent.com/1449852/84692497-f3569a80-af13-11ea-90e3-405817b37669.png)
