### ISSUE TITLE
Masked TexField `onChange` event is not triggered after a value is masked.

### ISSUE THREAD

**Issue by atogle** [CMSgov/design-system#630]
**Describe the bug**
I have a `TextField` with a `currency` mask with an `onChange` event handler that updates the application state. When the value is masked/changed the `onChange` event does not fire.

**To Reproduce**
1. Setup a `TextField` with a `currency` mask and bind an `onChange` event that stores the value in a variable.
2. Enter "abcd" into the field and blur. The value does not change in the `TextField` and matches the variable.
3. Edit the field by prepending 100 so that field reads "100ABCD" and then blur. The `TextField` masks its value to $100 but the variable still equals "100ABCD".

**Expected behavior**
Since the `TextField` value is changing, I would expect the `onChange` event to fire.

**Screenshots**
![currency-textfield](https://user-images.githubusercontent.com/446930/75171449-a434f180-56f9-11ea-828d-6b76e953ca70.gif)

**Desktop:**
 - OS: MacOS
 - Browser Chrome
 - Version 79

**Additional Context**
This was discovered using version 3.4.1 but also confirmed with 3.6.0.

**Comment by bernardwang** [comment]
@atogle In that example it looks like you aren't using `unmaskValue` in `onChange` before saving the value to store. Including the `unmaskValue` would prevent those non numeric characters from being saved in the first place. The ["Controlled Example"](http://localhost:3000/components/masked-field/) might be a useful reference.

The reason why the mask doesn't trigger the `onChange` is because its not considered user input. The mask is only intended to add formatting for readability when a user blurs from a field.

**Comment by bernardwang** [comment]
@atogle After discussing it some more with the team, we decided we will make the change to trigger `onChange` after the field is masked. I still recommend using `unmaskValue` in `onChange` like the example, but this change will help prevent this behavior in the future.

Tracked here: https://jira.cms.gov/browse/WNMGDS-387

**Comment by atogle** [comment]
Thank you for the update!

**Comment by bernardwang** [comment]
@atogle An update, we are actually still deciding the best way to handle this issue. In the meantime, I would recommend using either of these two solutions:
1. [Solution described earlier](https://github.com/CMSgov/design-system/issues/630#issuecomment-593646627)
2. Use the `onBlur` prop to receive the masked value. Since masking doesn't happen on user input, and only on blur, this is another "correct" way to obtain the formatted value.
