### ISSUE TITLE
Modal Dialog - allow for flexibility of tabindex - a11y issue

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#631]
**Description**

Would like to add tabindex=-1 to container of the modal dialog component. 

Currently, the modal window is only reading out the heading level one, and the Add generic button. This is probably due to the button being focused when the modal is opened. Users with visual issues may not understand why they're being prompted to add a generic without the entire modal being read aloud.

**Possible Remediation:**
Setting focus on the modal window's container instead of the button should cause the entire modal to be read aloud. Even if some screen readers do not honor this, users will be able to cursor through the modal and hear all the relevant information.

- Add a tabindex="-1" to the container so it can take keyboard focus. 
- Focus should still be trapped inside the modal once users press TAB

`<div
  aria-labelledby="dialog-title"
  class="ds-c-dialog ds-base"
  id="react-aria-modal-dialog"
  role="dialog"
  tabindex="-1">`

**Additional information** 
- related ticket [https://jira.cms.gov/browse/MCT-1825](https://jira.cms.gov/browse/MCT-1825)

**WCAG Guidance:** [Keyboard: Understanding SC 2.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/10236001/75258485-824c7500-57b4-11ea-81b0-39406de611a9.png">

**Comment by bernardwang** [comment]
@davidakennedy Thoughts on this? It makes sense to me, but it sounds like we would have to stop auto focusing on the button. Not sure if theres more context behind that behavior

**Comment by davidakennedy** [comment]
We can do this, and it won't affect the accessibility negatively. Modals should either focus on the whole thing first, or a button or input first— either way is fine.

I think this is a good thing to do, as it makes the dialog more flexible depending on the content needed to be in it.

We'll have to test it out, of course. In my current testing, NVDA reads out more than just the title, so mileage will vary.

A related idea that could also help @SparrowSpit here: `aria-labelledby` can take multiple IDs, so it would announce more than one item. Like: `aria-labelledby="dialog-title dialog-body"`. We could make that a prop so people could pass in multiple IDs.

**Comment by davidakennedy** [comment]
I was experimenting with this, and I think it may be possible to do this without making any changes in the core component. This is because most of the functional comes from this [React modal.
](https://github.com/davidtheclark/react-aria-modal)

If you check out its props, it provides an option to move the focus to the container and not the first focusable element. Also, you can pass an additional ID via the `titleId` prop, that way screen readers will associate two labels with it, and usually announce both. These can be added in the component created from the core component. Like:

```js
focusDialog={true}
titleId="dialog-title dialog-content"
```

You'd also need to make sure that a `div` or `p` element somewhere in your modal had an id of `dialog-content`.

It may be better to make changes at the core component level, but I like the idea of adding another example showing people how to do this. Thoughts?
