### ISSUE TITLE
TextField with 'currency' mask shows error when data contains commas

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/design-system#702]
**Describe the bug**
We're using the text field and when the data has commas the border goes red and the hover message is "Please match the requested format".

**To Reproduce**
1. Go to a text field that has a "currency" mask set.
2. enter a large number that contains commas
3. See the red border.
4. hover over the red border and see "Please match the requested format"

**Expected behavior**
Text fields with currency mask should accept values with commas

**Screenshots**

![Screen Shot 2020-05-21 at 12 56 27 PM (2)](https://user-images.githubusercontent.com/58570843/82588755-387fea80-9b69-11ea-8f32-e54ae55d9ce4.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Browser Firefox
 - Version 76.0.1

**Comment by line47** [comment]
Hey @pphillips-fearless What application is this for? 
is this for a medicare or healthcare design system? 

I'm asking because the core CMS Design System masked field component https://design.cms.gov/components/masked-field/ does not set up error handling.

I'm guessing this has been set up at a child design system level 
- Healthcare child design system repo
https://github.cms.gov/CMS-WDS/ds-healthcare-gov

- Medicare child design system repo 
https://github.cms.gov/MedicareGov/ds-site-package

**Comment by pphillips-fearless** [comment]
This is for the CMS eAPD (https://github.com/18F/cms-hitech-apd).

The link you provided (https://design.cms.gov/components/masked-field/) actually shows the issue I'm reporting (if you view it in Firefox).  The currency fields there have numbers with commas and the red outline around the boxes, and if you hover over the red edge you'll see "Please match the requested format".

From a quick google search on that message, it seems to be related to the use of "pattern" on the underlying input control.

**Comment by line47** [comment]
Thanks for clarifying @pphillips-fearless I missed the reference to Firefox in your original posting ☕

**Comment by line47** [comment]
Tracked here https://jira.cms.gov/browse/WNMGDS-483
