### ISSUE TITLE
[WNMGDS-507]: Choicelist: Cannot read property 'checked' of null

### ISSUE THREAD

**Issue by llimllib** [CMSgov/design-system#717]
[WNMGDS-507](https://jira.cms.gov/browse/WNMGDS-507)

**Describe the bug**

About once a minute, the MCT frontend records a `Cannot read property 'checked' of null` error in the Choicelist component, at this line: https://github.com/CMSgov/design-system/blob/6b0e84b7f66c8d5d3bbe2272c037e2c938404dcf/packages/design-system/src/components/ChoiceList/Choice.jsx#L50

presumably `this.input` is null when the component is receiving an `unchecked` event, for some reason that I don't know. I see the error happening on both Chrome and Edge in our new relic stats; I've never reproduced it myself.

**To Reproduce**

see below

**Expected behavior**

The choicelist component doesn't throw errors

**Screenshots**
<img width="1215" alt="JavaScript Errors 2020-06-12 10-25-20" src="https://user-images.githubusercontent.com/7150/84513152-0a3c8900-ac97-11ea-8efc-e9df653ecd8f.png">

**Desktop (please complete the following information):**
 - OS: unknown
 - Browser chrome, edge

**Comment by llimllib** [comment]
I found a reproducer! It seems to be related to keyboard navigation maybe?

1. Go to https://www.medicare.gov/plan-compare/#/questions/?year=2020&lang=en
2. choose `Medicare Advantage Plan`
3. enter any valid zip code
4. from now on, navigate with keyboard!
5. tab to the next field, then choose `Extra help from social security` with down arrows
6. tab to the next field, choose `I get a partial amount of Extra Help`
7. tab to the next field, and hit the down arrow rapidly. Sometimes you'll get the error! I find that sometimes I have to shift-tab up to the previous field, change an option, then tab back to it, but I can make it happen. I will post a screen recording of this behavior to the slack channel

**Comment by nichia** [comment]
In jira: https://jira.cms.gov/browse/WNMGDS-507

**Comment by Karak888** [comment]
@bernardwang can you please let @mliupaeter know when this is going to be released?  This is in Prod.

**Comment by bernardwang** [comment]
@nichia found out the error was coming from uncontrolled `<Choice>` inside checked children. Uncontrolled `<Choice>` components use an event emitter that was bring bound to `this`. Because the `<Choice>` was inside a checked children, the component would remount and the `this` instance became incorrect. 

@llimllib We are aiming to include the fix in the CMSDS v2 release in around 3-4 weeks, but you should be able to immediately fix this by making the checked children `<Choice>` components controlled. It's a bit more to manage in your form state, but thats the fastest solution, let me know if you have any questions with this. If you want to get the official fix in faster, you can also adopt the v2 beta, but that will involve upgrading a major version and some other changes
